version: "3.7"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - SERVER_PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    entrypoint: /bin/sh
    command: -c "yarn start:dev"